version: '3'

services:
  changedetectionio:
    image: dgtlmoon/changedetection.io:0.39.10
    container_name: changedetectionio
    restart: unless-stopped
    networks:
      - app-network
    ports: 
      - "127.0.0.1:5000:5000"
    volumes:
      - ./datastore:/datastore

  webserver:
    image: nginx:mainline
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/conf.d:/etc/nginx/conf.d
      - ./nginx-conf/default.d:/etc/nginx/default.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - changedetectionio
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

